services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.2
    container_name: socket-proxy
    pull_policy: always
    restart: unless-stopped
    ports:
      - "2375:2375"
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - INFO=1
      - POST=0
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock