services:
  portainer:
    image: portainer/portainer-ce:2.43.0
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik
    labels:
      - "homepage.group=Core VM"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.png"
      - "homepage.href=https://portainer.${DOMAIN}"
      - "homepage.description=Docker Management"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    dns:
      - 192.168.1.4
      - 1.1.1.1

volumes:
  portainer_data:

networks:
  traefik:
    external: true