services:
  homepage-init:
    image: alpine/git:latest
    container_name: homepage-init
    entrypoint: sh
    command: >
      -c "git clone https://github.com/nathanryder/script-libraries /repo &&
      cp -r /repo/docker/homepage/config/. /app/config/"
    volumes:
      - ./config:/config:ro
      - homepage_data:/app/config
    restart: no

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - homepage_data:/app/config
    environment:
    - HOMEPAGE_ALLOWED_HOSTS=homepage.${DOMAIN}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

volumes:
  homepage_data:

networks:
  traefik:
    external: true