services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - homepage_data:/app/config
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "homepage.group=Core VM"
      - "homepage.name=Homepage"
      - "homepage.icon=homepage.png"
      - "homepage.href=https://homepage.${DOMAIN}"

volumes:
  homepage_data:

networks:
  traefik:
    external: true