services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    pull_policy: always
    restart: unless-stopped
    ports:
      - "7070:7070"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    devices:
      - /dev/kmsg
    privileged: true