services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    pull_policy: always
    restart: unless-stopped
    ports:
      - "7070:8080"
    command:
      - "--docker=unix:///var/run/docker.sock"
      - "--docker_only=true"
      - "--store_container_labels=true"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    devices:
      - /dev/kmsg
    privileged: true