global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['192.168.1.3:9100']
        labels:
          instance: HL-HV01P
      - targets: ['192.168.1.4:9100']
        labels:
          instance: HL-CORE01V
      - targets: ['192.168.1.5:9100']
        labels:
          instance: HL-SRV01V
      - targets: ['192.168.1.7:9100']
        labels:
          instance: HL-OBS01V

  - job_name: traefik
    static_configs:
      - targets: ['192.168.1.4:8082']
        labels:
          instance: HL-CORE01V